-- Admin panel: published flag, auto-increment ids, admin-only writes via RLS.
-- The admin role lives in auth.users.raw_app_meta_data (only writable with the
-- service role, so users can't self-escalate) and travels in the JWT, which is
-- what the policies below read.

-- a) published + updated_at
alter table public.listings
  add column if not exists published  boolean     not null default true,
  add column if not exists updated_at timestamptz not null default now();

-- reuses public.set_updated_at() from 007_create_subscriptions.sql
drop trigger if exists listings_updated_at on public.listings;
create trigger listings_updated_at
  before update on public.listings
  for each row execute function public.set_updated_at();

-- b) id was seeded with explicit integers and has no sequence — convert to
-- identity so inserts can omit it. Guarded so the migration is re-runnable.
do $$
begin
  if not exists (
    select 1 from pg_attribute
    where attrelid = 'public.listings'::regclass
      and attname = 'id' and attidentity <> ''
  ) then
    alter table public.listings
      alter column id add generated by default as identity;
  end if;
end $$;

-- Without this the first insert would collide with the seeded ids (23505)
select setval(
  pg_get_serial_sequence('public.listings', 'id'),
  coalesce((select max(id) from public.listings), 0) + 1,
  false
);

-- c) Read: public only sees published; admin sees everything (policies OR together)
drop policy if exists "listings_public_read" on public.listings;
drop policy if exists "listings_select_published" on public.listings;
drop policy if exists "listings_select_admin" on public.listings;

create policy "listings_select_published"
  on public.listings for select
  using (published = true);

create policy "listings_select_admin"
  on public.listings for select to authenticated
  using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- d) Writes: admin only
drop policy if exists "listings_insert_admin" on public.listings;
drop policy if exists "listings_update_admin" on public.listings;
drop policy if exists "listings_delete_admin" on public.listings;

create policy "listings_insert_admin"
  on public.listings for insert to authenticated
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "listings_update_admin"
  on public.listings for update to authenticated
  using      ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "listings_delete_admin"
  on public.listings for delete to authenticated
  using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- e) Storage: admin writes on listing-images (public read already exists from 004)
drop policy if exists "listing_images_admin_insert" on storage.objects;
drop policy if exists "listing_images_admin_update" on storage.objects;
drop policy if exists "listing_images_admin_delete" on storage.objects;

create policy "listing_images_admin_insert"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'listing-images'
    and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "listing_images_admin_update"
  on storage.objects for update to authenticated
  using (bucket_id = 'listing-images'
    and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check (bucket_id = 'listing-images'
    and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "listing_images_admin_delete"
  on storage.objects for delete to authenticated
  using (bucket_id = 'listing-images'
    and (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- f) Bootstrap the single admin account. Idempotent; if the account doesn't
-- exist yet, register it first and re-run this UPDATE. The user must log out
-- and back in afterwards so the JWT picks up the new claim.
update auth.users
set raw_app_meta_data =
  coalesce(raw_app_meta_data, '{}'::jsonb) || jsonb_build_object('role', 'admin')
where email = 'vigarioignacio@gmail.com';
